title: AI Kitchen
description: AI and Agent Kitchen
theme: minima
header_pages:
  - about.md
minima:
  show_excerpts: true
  social_links:
    - title: aikitchen
      icon: github
      url: "https://github.com/mvervuurt/aikitchen"
