title: AI Kitchen
description: AI and Agents Kitchen. For more info, visit <a href="https://github.com/mvervuurt/aikitchen">aikitchen</a>
theme: minima
# remote_theme: jekyll/minima
header_pages:
  - about.md
minima:
  show_excerpts: true
  social_links:
    - title: aikitchen
      icon: github
      url: "https://github.com/mvervuurt/aikitchen"
