title: AI Kitchen
description: AI and Agents Kitchen  <br> <a href="https://github.com/mvervuurt/aikitchen">aikitchen</a>
remote_theme: jekyll/minima
# theme: minima
header_pages:
  - about.md
minima:
  show_excerpts: true
  social_links:
    - title: aikitchen
      icon: github
      url: "https://github.com/mvervuurt/aikitchen"
